name: plumbus
description: Todos tem um plumbs em casa.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  localization: ^2.1.0
  shared_preferences: ^2.2.0
  mocktail: ^1.0.0
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  multiple_result: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lang/
    - assets/images/